/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import CoinList from "../components/CoinList";
import Coins from "../components/Coins";
import SearchBar from "../components/SearchBar";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home({ filteredCoins }) {
  const [search, setSearch] = useState('')

  const allCoins = filteredCoins.filter(coin =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  )

  const handleChange = e => {
    e.preventDefault()
    setSearch(e.target.value.toLowerCase())
  }


  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>CoinSpace</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <SearchBar type="text" placeholder="Search Your CryptoCurrency" onChange={handleChange} />



        <Coins />



        <CoinList filteredCoins={allCoins} />






      </div>
    </>
  );
}


export const getServerSideProps = async () => {
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&order=market_cap_desc&per_page=250&page=1&sparkline=false')

  const filteredCoins = await res.json();
  return {
    props: { filteredCoins }, // will be passed to the page component as props
  }
}